//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.FurnitureReceipts = new HashSet<FurnitureReceipt>();
            this.RoomFurnituresDetails = new HashSet<RoomFurnituresDetail>();
        }
    
        public string FurnitureId { get; set; }
        public string FurnitureName { get; set; }
        public string FurnitureType { get; set; }
        public byte[] FurnitureAvatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurnitureReceipt> FurnitureReceipts { get; set; }
        public virtual FurnitureStorage FurnitureStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomFurnituresDetail> RoomFurnituresDetails { get; set; }
    }
}
