//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsReceipt
    {
        public string GoodsReceiptId { get; set; }
        public string ServiceId { get; set; }
        public string StaffId { get; set; }
        public Nullable<double> ImportPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
