//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomFurnituresDetail
    {
        public int RoomFurnituresDetailId { get; set; }
        public string FurnitureId { get; set; }
        public string RoomId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Room Room { get; set; }
    }
}
