//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceUsing
    {
        public int ServiceUsingId { get; set; }
        public string ServiceId { get; set; }
        public string RentalContractId { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual RentalContract RentalContract { get; set; }
        public virtual Service Service { get; set; }
    }
}
